config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/feed'

  get 'pages/about'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def feed
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class='title'> 
    <%= render 'shared/nav' %>
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Landon George,
   Mark Ward and
   Larsen James
</p>
<a href="https://github.com/up2l8-0/News-App">Link to our github</a>

app/views/pages/feed.html.erb
<div>
   <div class='feed-story'>
      <h1>Tree Turtle!</h1>
      <h3>Random Happenstance</h3>
      <p>Today in Anytown USA, a turtle got stuck in a tree.
      Ironically it was cat-free-tree day.
      When the turtle was finally freed from it's wooden prison,
      the upset mayor decided to hold a second cat-free-tree day.</p>
       <img src="http://kids.nationalgeographic.com/content/dam/kids/photos/animals/Reptiles/A-G/green-sea-turtle-closeup-underwater.adapt.945.1.jpg" />

   </div>
   
   <div class='feed-story'>
      <h1>Evil Octopi!</h1>
      <h3>Criminal Marine Life</h3>
      <p>This month has seen a rise in octopus attacks.
      Today alone 3 whole people have been mugged by the octopi.
      The victims, though mentally scarred, are uninjured,
      and police officers are working around the clock to bring these tentacled fiends to justice.</p>
      <img src='https://s-media-cache-ak0.pinimg.com/736x/7e/a4/e4/7ea4e4e721344aec6d0cac99790ca0fc--octopus-costume-octopus-art.jpg'  />
   </div>
</div>

app/views/pages/home.html.erb
<div>
   <div class='title'>
      <h1>Homepage</h1>
   </div>
   <div>
      <p>You know where to find me ;)</p>
   </div>
</div>

app/views/shared/_nav.html.erb
<div class='title'>
   <%= link_to 'Home', root_path %>
   <%= link_to 'Feed', pages_feed_path %> 
   <%= link_to 'About', pages_about_path %> 
</div>